package ventanas;

import clases.Administrador;
import herramientas.ComponentesDeVentana;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

public class Administracion extends javax.swing.JFrame {
    
    public static String imagenDeEleccion;
    public static Administracion ventanaAdministracion;
    public static Administrador administrador;
    
    public Administracion() {
        initComponents();
        setSize(1100,700);
        setResizable(false);
        setTitle("ADMINISTRACIÓN");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventanaAdministracion = this;
        
        lblNombreApellido.setText((administrador.getNombres() + " " + 
                administrador.getApellidos()).toUpperCase());
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoBlanco2.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoPrincipal, 
                "src/imagenes/logoPrincipal.png");
        ComponentesDeVentana.redondearBordesJLabel(lblNombreApellido, 10, 1);
        
        ComponentesDeVentana.ajustarImagenAJButton(btnGestionAdministradores, 
                "src/imagenes/gestionAdministradores.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnGestionBinomios, 
                "src/imagenes/gestionBinomios.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnGestionCivil, 
                "src/imagenes/gestionCivil.png");
        
        ComponentesDeVentana.redondearBordesJButton(btnGestionAdministradores, 20, 2, Color.GRAY);
        ComponentesDeVentana.redondearBordesJButton(btnGestionBinomios, 20, 2, Color.GRAY);
        ComponentesDeVentana.redondearBordesJButton(btnGestionCivil, 20, 2, Color.GRAY);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("imagenes/logoCNEConFondo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionCivil = new javax.swing.JButton();
        btnGestionBinomios = new javax.swing.JButton();
        btnGestionAdministradores = new javax.swing.JButton();
        lblGestionCivil = new javax.swing.JLabel();
        lblGestionDe1 = new javax.swing.JLabel();
        lblGestionDe2 = new javax.swing.JLabel();
        lblAdministradores = new javax.swing.JLabel();
        lblDerechosReservados = new javax.swing.JLabel();
        lblBinomios = new javax.swing.JLabel();
        lblNombreApellido = new javax.swing.JLabel();
        lblLogoPrincipal = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionCivil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionCivilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionCivilMouseExited(evt);
            }
        });
        btnGestionCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionCivilActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 310, 150, 150));

        btnGestionBinomios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionBinomios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionBinomiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionBinomiosMouseExited(evt);
            }
        });
        btnGestionBinomios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionBinomiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionBinomios, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 310, 150, 150));

        btnGestionAdministradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionAdministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionAdministradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionAdministradoresMouseExited(evt);
            }
        });
        btnGestionAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionAdministradoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 310, 150, 150));

        lblGestionCivil.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblGestionCivil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionCivil.setText("Gestión Civil");
        getContentPane().add(lblGestionCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 480, 150, -1));

        lblGestionDe1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblGestionDe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionDe1.setText("Gestión de");
        getContentPane().add(lblGestionDe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 480, 150, -1));

        lblGestionDe2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblGestionDe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionDe2.setText("Gestión de");
        getContentPane().add(lblGestionDe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 480, 150, 30));

        lblAdministradores.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblAdministradores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministradores.setText("Administradores");
        getContentPane().add(lblAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 500, 150, 30));

        lblDerechosReservados.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblDerechosReservados.setText("EPN © Todos los Derechos Reservados.");
        getContentPane().add(lblDerechosReservados, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 300, -1));

        lblBinomios.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblBinomios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBinomios.setText("Binomios");
        getContentPane().add(lblBinomios, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 500, 150, 30));

        lblNombreApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreApellido.setText("NOMBRE APELLIDO");
        getContentPane().add(lblNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 20));

        lblLogoPrincipal.setToolTipText("");
        getContentPane().add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -70, 800, 450));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionCivilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionCivilMouseEntered
        // TODO add your handling code here:
        btnGestionCivil.setSize(btnGestionCivil.getWidth() + 10, 
                btnGestionCivil.getHeight() + 10);
    }//GEN-LAST:event_btnGestionCivilMouseEntered

    private void btnGestionCivilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionCivilMouseExited
        // TODO add your handling code here:
        btnGestionCivil.setSize(btnGestionCivil.getWidth() - 10, 
                btnGestionCivil.getHeight() - 10);
    }//GEN-LAST:event_btnGestionCivilMouseExited

    private void btnGestionBinomiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionBinomiosMouseEntered
        // TODO add your handling code here:
        btnGestionBinomios.setSize(btnGestionBinomios.getWidth() + 10, 
                btnGestionBinomios.getHeight() + 10);
    }//GEN-LAST:event_btnGestionBinomiosMouseEntered

    private void btnGestionBinomiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionBinomiosMouseExited
        // TODO add your handling code here:
        btnGestionBinomios.setSize(btnGestionBinomios.getWidth() - 10, 
                btnGestionBinomios.getHeight() - 10);
    }//GEN-LAST:event_btnGestionBinomiosMouseExited

    private void btnGestionAdministradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAdministradoresMouseEntered
        // TODO add your handling code here:
        btnGestionAdministradores.setSize(btnGestionAdministradores.getWidth() + 10, 
                btnGestionAdministradores.getHeight() + 10);
    }//GEN-LAST:event_btnGestionAdministradoresMouseEntered

    private void btnGestionAdministradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAdministradoresMouseExited
        // TODO add your handling code here:
        btnGestionAdministradores.setSize(btnGestionAdministradores.getWidth() - 10, 
                btnGestionAdministradores.getHeight() - 10);
    }//GEN-LAST:event_btnGestionAdministradoresMouseExited

    private void btnGestionCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCivilActionPerformed
        this.ventanaAdministracion.setEnabled(false);
        GestionCivil gestionCivil = new GestionCivil();
        gestionCivil.setVisible(true);
    }//GEN-LAST:event_btnGestionCivilActionPerformed

    private void btnGestionBinomiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionBinomiosActionPerformed
        this.ventanaAdministracion.setEnabled(false);
        GestionBinomios gestionBinomios = new GestionBinomios();
        gestionBinomios.setVisible(true);
    }//GEN-LAST:event_btnGestionBinomiosActionPerformed

    private void btnGestionAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAdministradoresActionPerformed
        this.ventanaAdministracion.setEnabled(false);
        GestionAdministradores gestionAdministradores = 
                new GestionAdministradores();
        gestionAdministradores.setVisible(true);
    }//GEN-LAST:event_btnGestionAdministradoresActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmPrincipal.ventanaPrincipal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.ventanaAdministracion = null;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionAdministradores;
    private javax.swing.JButton btnGestionBinomios;
    private javax.swing.JButton btnGestionCivil;
    private javax.swing.JLabel lblAdministradores;
    private javax.swing.JLabel lblBinomios;
    private javax.swing.JLabel lblDerechosReservados;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGestionCivil;
    private javax.swing.JLabel lblGestionDe1;
    private javax.swing.JLabel lblGestionDe2;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JLabel lblNombreApellido;
    // End of variables declaration//GEN-END:variables
}
