package ventanas;

import clases.BordeRedondeado;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import clases.*;

public class FrmPrincipal extends javax.swing.JFrame {
    
    public static String imagenDeEleccion;

    public FrmPrincipal() {
        initComponents();
        setSize(1100,700);
        setResizable(false);
        setTitle("CONSEJO NACIONAL ELECTORAL");
        setLocationRelativeTo(null);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoBlanco2.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoPrincipal, 
                "src/imagenes/logoPrincipal.png");
        
        ComponentesDeVentana.ajustarImagenAJButton(btnAdministracion,
                "src/imagenes/administracion.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnResultados,
                "src/imagenes/resultados.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnVotoTelematico,
                "src/imagenes/votoTelematico.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnConsultaLugarVotacion,
                "src/imagenes/lugarVotacion.png");  
        
        ComponentesDeVentana.redondearBordesJButton(btnAdministracion, Color.GRAY, 4);
        ComponentesDeVentana.redondearBordesJButton(btnResultados, Color.GRAY, 4);
        ComponentesDeVentana.redondearBordesJButton(btnVotoTelematico, Color.GRAY, 4);
        ComponentesDeVentana.redondearBordesJButton(btnConsultaLugarVotacion, Color.GRAY, 4);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("imagenes/logoCNE.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministracion = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        btnVotoTelematico = new javax.swing.JButton();
        btnConsultaLugarVotacion = new javax.swing.JButton();
        lblLogoPrincipal = new javax.swing.JLabel();
        lblAdministracion = new javax.swing.JLabel();
        lblResultados = new javax.swing.JLabel();
        lblVotoTelematico = new javax.swing.JLabel();
        lblConsultaTuLugarDeVotacion = new javax.swing.JLabel();
        lblConsultaTuLugarDeVotacion1 = new javax.swing.JLabel();
        lblDerechosReservados = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdministracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdministracionMouseExited(evt);
            }
        });
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, 150));

        btnResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResultadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResultadosMouseExited(evt);
            }
        });
        getContentPane().add(btnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 150, 150));

        btnVotoTelematico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVotoTelematico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVotoTelematicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVotoTelematicoMouseExited(evt);
            }
        });
        btnVotoTelematico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotoTelematicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVotoTelematico, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 150, 150));

        btnConsultaLugarVotacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaLugarVotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultaLugarVotacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultaLugarVotacionMouseExited(evt);
            }
        });
        btnConsultaLugarVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaLugarVotacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaLugarVotacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, 150, 150));

        lblLogoPrincipal.setToolTipText("");
        getContentPane().add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -70, 800, 450));

        lblAdministracion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblAdministracion.setText("Administración");
        getContentPane().add(lblAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 480, -1, -1));

        lblResultados.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblResultados.setText("Resultados");
        getContentPane().add(lblResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 480, -1, -1));

        lblVotoTelematico.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblVotoTelematico.setText("Voto Telemático");
        getContentPane().add(lblVotoTelematico, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 480, -1, -1));

        lblConsultaTuLugarDeVotacion.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblConsultaTuLugarDeVotacion.setText("de votación");
        getContentPane().add(lblConsultaTuLugarDeVotacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 503, 110, 30));

        lblConsultaTuLugarDeVotacion1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblConsultaTuLugarDeVotacion1.setText("Consulta tu lugar");
        getContentPane().add(lblConsultaTuLugarDeVotacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 150, 30));

        lblDerechosReservados.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lblDerechosReservados.setText("EPN © Todos los Derechos Reservados.");
        getContentPane().add(lblDerechosReservados, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 300, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministracionMouseEntered
        // TODO add your handling code here:
        btnAdministracion.setSize(btnAdministracion.getWidth() + 10, 
                btnAdministracion.getHeight() + 10);
    }//GEN-LAST:event_btnAdministracionMouseEntered

    private void btnAdministracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdministracionMouseExited
        // TODO add your handling code here:
        btnAdministracion.setSize(btnAdministracion.getWidth() - 10, 
                btnAdministracion.getHeight() - 10);
    }//GEN-LAST:event_btnAdministracionMouseExited

    private void btnResultadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMouseEntered
        // TODO add your handling code here:
        btnResultados.setSize(btnResultados.getWidth() + 10, 
                btnResultados.getHeight() + 10);
    }//GEN-LAST:event_btnResultadosMouseEntered

    private void btnResultadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMouseExited
        // TODO add your handling code here:
        btnResultados.setSize(btnResultados.getWidth() - 10, 
                btnResultados.getHeight() - 10);
    }//GEN-LAST:event_btnResultadosMouseExited

    private void btnVotoTelematicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVotoTelematicoMouseEntered
        // TODO add your handling code here:
        btnVotoTelematico.setSize(btnVotoTelematico.getWidth() + 10, 
                btnVotoTelematico.getHeight() + 10);
    }//GEN-LAST:event_btnVotoTelematicoMouseEntered

    private void btnVotoTelematicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVotoTelematicoMouseExited
        // TODO add your handling code here:
        btnVotoTelematico.setSize(btnVotoTelematico.getWidth() - 10, 
                btnVotoTelematico.getHeight() - 10);
    }//GEN-LAST:event_btnVotoTelematicoMouseExited

    private void btnConsultaLugarVotacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLugarVotacionMouseEntered
        // TODO add your handling code here:
        btnConsultaLugarVotacion.setSize(btnConsultaLugarVotacion.getWidth() + 10, 
                btnConsultaLugarVotacion.getHeight() + 10);
    }//GEN-LAST:event_btnConsultaLugarVotacionMouseEntered

    private void btnConsultaLugarVotacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLugarVotacionMouseExited
        // TODO add your handling code here:
        btnConsultaLugarVotacion.setSize(btnConsultaLugarVotacion.getWidth() - 10, 
                btnConsultaLugarVotacion.getHeight() - 10);
    }//GEN-LAST:event_btnConsultaLugarVotacionMouseExited

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        IniciarSesionAdministrador iniciarSesionAdministrador = 
                new IniciarSesionAdministrador();
        iniciarSesionAdministrador.setVisible(true);
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnVotoTelematicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotoTelematicoActionPerformed
        // TODO add your handling code here:
        imagenDeEleccion = "src/imagenes/votoTelematico.png";
        IniciarSesionCedula iniciarSesionCedula = new IniciarSesionCedula();
        iniciarSesionCedula.setVisible(true);
    }//GEN-LAST:event_btnVotoTelematicoActionPerformed

    private void btnConsultaLugarVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaLugarVotacionActionPerformed
        // TODO add your handling code here:
        imagenDeEleccion = "src/imagenes/lugarVotacion.png";
        IniciarSesionCedula iniciarSesionCedula = new IniciarSesionCedula();
        iniciarSesionCedula.setVisible(true);
    }//GEN-LAST:event_btnConsultaLugarVotacionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnConsultaLugarVotacion;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnVotoTelematico;
    private javax.swing.JLabel lblAdministracion;
    private javax.swing.JLabel lblConsultaTuLugarDeVotacion;
    private javax.swing.JLabel lblConsultaTuLugarDeVotacion1;
    private javax.swing.JLabel lblDerechosReservados;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblVotoTelematico;
    // End of variables declaration//GEN-END:variables
}
