/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import herramientas.ComponentesDeVentana;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick
 */
public class GestionAdministradores extends javax.swing.JFrame {

    /**
     * Creates new form GestionAdministradores
     */
    
    DefaultTableModel tablaAdministradores;
    public GestionAdministradores() {
        initComponents();
        
        setResizable(false);
        setTitle("GESTIÓN DE BINOMIOS");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoBlanco2.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoPrincipal, 
                "src/imagenes/logoPrincipal.png");
        
        pnlDatosAdministradores.setOpaque(false);
        pnlDatosAdministradores.setVisible(false);
        
        ComponentesDeVentana.ajustarImagenAJButton(btnNuevo, "src/imagenes/nuevo.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEliminar, "src/imagenes/eliminar.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEditar, "src/imagenes/editar.png");

        btnNuevo.setOpaque(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setBorderPainted(false);
        btnEliminar.setOpaque(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setBorderPainted(false);
        btnEditar.setOpaque(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setBorderPainted(false);
        
        tablaAdministradores = new DefaultTableModel();
        tablaAdministradores.addColumn("Nombres");
        tablaAdministradores.addColumn("Apellidos");
        tablaAdministradores.addColumn("Usuario");
        tblAdministradores.setModel(tablaAdministradores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblLogoPrincipal = new javax.swing.JLabel();
        pnlDatosAdministradores = new javax.swing.JPanel();
        lblDatosAdministrador = new javax.swing.JLabel();
        txtPrimerNombrePresidente = new javax.swing.JTextField();
        lblPrimerNombreAdministrador = new javax.swing.JLabel();
        lblSegundoNombreAdministrador = new javax.swing.JLabel();
        txtSegundoNombrePresidente = new javax.swing.JTextField();
        lblPrimerApellidoAdministrador = new javax.swing.JLabel();
        txtPrimerApellidoPresidente = new javax.swing.JTextField();
        lblSegundoApellidoAdministrador = new javax.swing.JLabel();
        txtSegundoApellidoPresidente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreDeUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministradores = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setPreferredSize(new java.awt.Dimension(1100, 700));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 340, 190));

        lblDatosAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDatosAdministrador.setText("Datos del administrador");

        lblPrimerNombreAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerNombreAdministrador.setText("Primer Nombre");

        lblSegundoNombreAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoNombreAdministrador.setText("Segundo Nombre");

        lblPrimerApellidoAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerApellidoAdministrador.setText("Primer Apellido");

        lblSegundoApellidoAdministrador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoApellidoAdministrador.setText("Segundo Apellido");

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");

        lblNombreUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreUsuario.setText("Nombre de usuario");

        lblContrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblContrasenia.setText("Contraseña");

        javax.swing.GroupLayout pnlDatosAdministradoresLayout = new javax.swing.GroupLayout(pnlDatosAdministradores);
        pnlDatosAdministradores.setLayout(pnlDatosAdministradoresLayout);
        pnlDatosAdministradoresLayout.setHorizontalGroup(
            pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAdministradoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatosAdministrador)
                    .addComponent(lblPrimerNombreAdministrador)
                    .addComponent(lblSegundoNombreAdministrador)
                    .addComponent(lblPrimerApellidoAdministrador)
                    .addComponent(lblSegundoApellidoAdministrador)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblContrasenia))
                .addGap(24, 24, 24)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrimerNombrePresidente)
                    .addComponent(txtSegundoNombrePresidente)
                    .addComponent(txtPrimerApellidoPresidente)
                    .addComponent(txtSegundoApellidoPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtNombreDeUsuario)
                    .addComponent(txtContrasenia))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosAdministradoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(264, 264, 264))
        );
        pnlDatosAdministradoresLayout.setVerticalGroup(
            pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAdministradoresLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblDatosAdministrador)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerNombreAdministrador)
                    .addComponent(txtPrimerNombrePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoNombreAdministrador)
                    .addComponent(txtSegundoNombrePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellidoAdministrador)
                    .addComponent(txtPrimerApellidoPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoApellidoAdministrador)
                    .addComponent(txtSegundoApellidoPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnGuardar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlDatosAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 430, 420));

        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFondo.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 65, 65));
        pnlFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 65, 65));

        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 65, 65));

        tblAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdministradores);

        pnlFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblFondo.setPreferredSize(new java.awt.Dimension(1100, 700));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        pnlDatosAdministradores.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblDatosAdministrador;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPrimerApellidoAdministrador;
    private javax.swing.JLabel lblPrimerNombreAdministrador;
    private javax.swing.JLabel lblSegundoApellidoAdministrador;
    private javax.swing.JLabel lblSegundoNombreAdministrador;
    private javax.swing.JPanel pnlDatosAdministradores;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tblAdministradores;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtNombreDeUsuario;
    private javax.swing.JTextField txtPrimerApellidoPresidente;
    private javax.swing.JTextField txtPrimerNombrePresidente;
    private javax.swing.JTextField txtSegundoApellidoPresidente;
    private javax.swing.JTextField txtSegundoNombrePresidente;
    // End of variables declaration//GEN-END:variables
}
