/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import herramientas.ComponentesDeVentana;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick
 */
public class GestionBinomios extends javax.swing.JFrame {

    /**
     * Creates new form GestionBinomios
     */
    DefaultTableModel tablaBinomios;
    
    public GestionBinomios() {
        initComponents();
        setSize(1100,700);
        setResizable(false);
        setTitle("GESTIÓN DE BINOMIOS");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoBlanco2.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoPrincipal, 
                "src/imagenes/logoPrincipal.png");
        
        pnlDatosBinomio.setOpaque(false);
        pnlDatosBinomio.setVisible(false);
        
        ComponentesDeVentana.ajustarImagenAJButton(btnNuevo, "src/imagenes/nuevo.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEliminar, "src/imagenes/eliminar.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEditar, "src/imagenes/editar.png");

        btnNuevo.setOpaque(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setBorderPainted(false);
        btnEliminar.setOpaque(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setBorderPainted(false);
        btnEditar.setOpaque(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setBorderPainted(false);
        
        tablaBinomios = new DefaultTableModel();
        tablaBinomios.addColumn("Lista");
        tablaBinomios.addColumn("Presidente/a");
        tablaBinomios.addColumn("Vicepresidente/a");
        tblBinomios.setModel(tablaBinomios);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("imagenes/logoCNEConFondo.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblLogoPrincipal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBinomios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        pnlDatosBinomio = new javax.swing.JPanel();
        lblNombreMovimientoPolitico = new javax.swing.JLabel();
        txtMovimientoPolitico = new javax.swing.JTextField();
        lblDatosPresidente = new javax.swing.JLabel();
        txtPrimerNombrePresidente = new javax.swing.JTextField();
        lblPrimerNombrePresidente = new javax.swing.JLabel();
        lblSegundoNombrePresidente = new javax.swing.JLabel();
        txtSegundoNombrePresidente = new javax.swing.JTextField();
        lblPrimerApellidoPresidente = new javax.swing.JLabel();
        txtPrimerApellidoPresidente = new javax.swing.JTextField();
        lblSegundoApellidoPresidente = new javax.swing.JLabel();
        txtSegundoApellidoPresidente = new javax.swing.JTextField();
        lblDatosVicepresidente = new javax.swing.JLabel();
        lblPrimerNombreVicepresidente = new javax.swing.JLabel();
        txtPrimerNombreVicepresidente = new javax.swing.JTextField();
        lblSegundoNombreVicepresidente = new javax.swing.JLabel();
        txtSegundoNombreVicepresidente = new javax.swing.JTextField();
        lblPrimerApellidoVicepresidente = new javax.swing.JLabel();
        txtPrimerApellidoVicepresidente = new javax.swing.JTextField();
        lblSegundoApellidoVicepresidente = new javax.swing.JLabel();
        txtSegundoApellidoVicepresidente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 340, 190));

        tblBinomios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblBinomios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBinomios.setAlignmentX(0.0F);
        tblBinomios.setAlignmentY(0.0F);
        jScrollPane2.setViewportView(tblBinomios);

        pnlFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlFondo.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 65, 65));
        pnlFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 65, 65));

        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 65, 65));

        lblNombreMovimientoPolitico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreMovimientoPolitico.setText("Nombre del movimiento político");

        lblDatosPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDatosPresidente.setText("Datos del candidato a presidente");

        lblPrimerNombrePresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerNombrePresidente.setText("Primer Nombre");

        lblSegundoNombrePresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoNombrePresidente.setText("Segundo Nombre");

        lblPrimerApellidoPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerApellidoPresidente.setText("Primer Apellido");

        lblSegundoApellidoPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoApellidoPresidente.setText("Segundo Apellido");

        lblDatosVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDatosVicepresidente.setText("Datos del candidato a vicepresidente");

        lblPrimerNombreVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerNombreVicepresidente.setText("Primer Nombre");

        lblSegundoNombreVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoNombreVicepresidente.setText("Segundo Nombre");

        lblPrimerApellidoVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPrimerApellidoVicepresidente.setText("Primer Apellido");

        lblSegundoApellidoVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSegundoApellidoVicepresidente.setText("Segundo Apellido");

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout pnlDatosBinomioLayout = new javax.swing.GroupLayout(pnlDatosBinomio);
        pnlDatosBinomio.setLayout(pnlDatosBinomioLayout);
        pnlDatosBinomioLayout.setHorizontalGroup(
            pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatosPresidente)
                    .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                            .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreMovimientoPolitico)
                                .addComponent(lblPrimerNombrePresidente)
                                .addComponent(lblSegundoNombrePresidente)
                                .addComponent(lblPrimerApellidoPresidente)
                                .addComponent(lblSegundoApellidoPresidente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMovimientoPolitico)
                                .addComponent(txtPrimerNombrePresidente)
                                .addComponent(txtSegundoNombrePresidente)
                                .addComponent(txtPrimerApellidoPresidente)
                                .addComponent(txtSegundoApellidoPresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                        .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                            .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrimerNombreVicepresidente)
                                .addComponent(lblDatosVicepresidente)
                                .addComponent(lblSegundoNombreVicepresidente)
                                .addComponent(lblPrimerApellidoVicepresidente)
                                .addComponent(lblSegundoApellidoVicepresidente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGuardar)
                                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrimerNombreVicepresidente)
                                    .addComponent(txtSegundoNombreVicepresidente)
                                    .addComponent(txtPrimerApellidoVicepresidente)
                                    .addComponent(txtSegundoApellidoVicepresidente, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlDatosBinomioLayout.setVerticalGroup(
            pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMovimientoPolitico)
                    .addComponent(txtMovimientoPolitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDatosPresidente)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerNombrePresidente)
                    .addComponent(txtPrimerNombrePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoNombrePresidente)
                    .addComponent(txtSegundoNombrePresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellidoPresidente)
                    .addComponent(txtPrimerApellidoPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoApellidoPresidente)
                    .addComponent(txtSegundoApellidoPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblDatosVicepresidente)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrimerNombreVicepresidente)
                    .addComponent(txtPrimerNombreVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoNombreVicepresidente)
                    .addComponent(txtSegundoNombreVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellidoVicepresidente)
                    .addComponent(txtPrimerApellidoVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSegundoApellidoVicepresidente)
                    .addComponent(txtSegundoApellidoVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnGuardar)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlDatosBinomio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 610, 570));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        pnlDatosBinomio.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionBinomios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatosPresidente;
    private javax.swing.JLabel lblDatosVicepresidente;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JLabel lblNombreMovimientoPolitico;
    private javax.swing.JLabel lblPrimerApellidoPresidente;
    private javax.swing.JLabel lblPrimerApellidoVicepresidente;
    private javax.swing.JLabel lblPrimerNombrePresidente;
    private javax.swing.JLabel lblPrimerNombreVicepresidente;
    private javax.swing.JLabel lblSegundoApellidoPresidente;
    private javax.swing.JLabel lblSegundoApellidoVicepresidente;
    private javax.swing.JLabel lblSegundoNombrePresidente;
    private javax.swing.JLabel lblSegundoNombreVicepresidente;
    private javax.swing.JPanel pnlDatosBinomio;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tblBinomios;
    private javax.swing.JTextField txtMovimientoPolitico;
    private javax.swing.JTextField txtPrimerApellidoPresidente;
    private javax.swing.JTextField txtPrimerApellidoVicepresidente;
    private javax.swing.JTextField txtPrimerNombrePresidente;
    private javax.swing.JTextField txtPrimerNombreVicepresidente;
    private javax.swing.JTextField txtSegundoApellidoPresidente;
    private javax.swing.JTextField txtSegundoApellidoVicepresidente;
    private javax.swing.JTextField txtSegundoNombrePresidente;
    private javax.swing.JTextField txtSegundoNombreVicepresidente;
    // End of variables declaration//GEN-END:variables
}
