/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.*;
import herramientas.ComponentesDeVentana;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import static ventanas.FrmPrincipal.listaBinomios;

/**
 *
 * @author Erick
 */
public class GestionBinomios extends javax.swing.JFrame {

    int filaSeleccionada;
    Binomio binomioSeleccionado;
    /**
     * Creates new form GestionBinomios
     */
    DefaultTableModel dtmTablaBinomios;
    
    public GestionBinomios() {
        initComponents();
        setSize(1100,700);
        setResizable(false);
        setTitle("GESTIÓN DE BINOMIOS");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoBlanco2.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoPrincipal, 
                "src/imagenes/logoPrincipal.png");
        
        pnlDatosBinomio.setOpaque(false);
        pnlDatosBinomio.setVisible(false);
        
        ComponentesDeVentana.ajustarImagenAJButton(btnNuevo, "src/imagenes/nuevo.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEliminar, "src/imagenes/eliminar.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnEditar, "src/imagenes/editar.png");
        ComponentesDeVentana.ajustarImagenAJButton(btnBuscar, "src/imagenes/buscar.png");

        btnNuevo.setOpaque(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setBorderPainted(false);
        btnEliminar.setOpaque(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setBorderPainted(false);
        btnEditar.setOpaque(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setBorderPainted(false);
        btnBuscar.setOpaque(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setBorderPainted(false);
        
        dtmTablaBinomios = new DefaultTableModel();
        dtmTablaBinomios.addColumn("Lista");
        dtmTablaBinomios.addColumn("Presidente/a");
        dtmTablaBinomios.addColumn("Vicepresidente/a");
        tblBinomios.setModel(dtmTablaBinomios);

        limpiarTablaDeBinomios();
        mostrarDatosDeBinomios();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("imagenes/logoCNEConFondo.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblLogoPrincipal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBinomios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        pnlDatosBinomio = new javax.swing.JPanel();
        lblNombreMovimientoPolitico = new javax.swing.JLabel();
        txtMovimientoPolitico = new javax.swing.JTextField();
        lblDatosPresidente = new javax.swing.JLabel();
        txtNombresPresidente = new javax.swing.JTextField();
        lbNombresPresidente = new javax.swing.JLabel();
        lblApellidosPresidente = new javax.swing.JLabel();
        txtApellidosPresidente = new javax.swing.JTextField();
        lblDatosVicepresidente = new javax.swing.JLabel();
        lblNombresVicepresidente = new javax.swing.JLabel();
        txtNombresVicepresidente = new javax.swing.JTextField();
        lblApellidosVicepresidente = new javax.swing.JLabel();
        txtApellidosVicepresidente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(lblLogoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 340, 190));

        tblBinomios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblBinomios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBinomios.setAlignmentX(0.0F);
        tblBinomios.setAlignmentY(0.0F);
        tblBinomios.setOpaque(false);
        jScrollPane2.setViewportView(tblBinomios);

        pnlFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlFondo.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 65, 65));

        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 65, 65));

        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 65, 65));

        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 65, 65));

        lblNombreMovimientoPolitico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombreMovimientoPolitico.setText("Nombre del movimiento político");

        lblDatosPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDatosPresidente.setText("Datos del candidato a presidente");

        lbNombresPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNombresPresidente.setText("Nombres");

        lblApellidosPresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblApellidosPresidente.setText("Apellidos");

        lblDatosVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDatosVicepresidente.setText("Datos del candidato a vicepresidente");

        lblNombresVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombresVicepresidente.setText("Nombres");

        lblApellidosVicepresidente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblApellidosVicepresidente.setText("Apellidos");

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosBinomioLayout = new javax.swing.GroupLayout(pnlDatosBinomio);
        pnlDatosBinomio.setLayout(pnlDatosBinomioLayout);
        pnlDatosBinomioLayout.setHorizontalGroup(
            pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidosVicepresidente)
                    .addComponent(lblDatosVicepresidente)
                    .addComponent(lblDatosPresidente)
                    .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                        .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreMovimientoPolitico)
                            .addComponent(lbNombresPresidente)
                            .addComponent(lblApellidosPresidente)
                            .addComponent(lblNombresVicepresidente))
                        .addGap(37, 37, 37)
                        .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombresVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMovimientoPolitico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombresPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlDatosBinomioLayout.setVerticalGroup(
            pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosBinomioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMovimientoPolitico)
                    .addComponent(txtMovimientoPolitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDatosPresidente)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombresPresidente)
                    .addComponent(txtNombresPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPresidente)
                    .addComponent(txtApellidosPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDatosVicepresidente)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombresVicepresidente)
                    .addComponent(txtNombresVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosBinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosVicepresidente)
                    .addComponent(txtApellidosVicepresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnGuardar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlFondo.add(pnlDatosBinomio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 610, 360));
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        pnlDatosBinomio.setVisible(false);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        obtenerBinomioSeleccionado();
        pnlDatosBinomio.setVisible(true);
        txtMovimientoPolitico.setText(binomioSeleccionado.getMovimientoPolitico().getNombre());
        txtNombresPresidente.setText(binomioSeleccionado.getPresidente().getNombres());
        txtApellidosPresidente.setText(binomioSeleccionado.getPresidente().getApellidos());
        txtNombresVicepresidente.setText(binomioSeleccionado.getVicepresidente().getNombres());
        txtApellidosVicepresidente.setText(binomioSeleccionado.getVicepresidente().getApellidos());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        pnlDatosBinomio.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        obtenerBinomioSeleccionado();
        listaBinomios.remove(binomioSeleccionado);
        limpiarTablaDeBinomios();
        mostrarDatosDeBinomios();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nuevoNombreMovimiento = txtMovimientoPolitico.getText();
        String nuevosNombresPresidente = txtNombresPresidente.getText();
        String nuevosApellidosPresidente = txtApellidosPresidente.getText();
        String nuevosNombresVicepresidente = txtNombresVicepresidente.getText();
        String nuevosApellidosVicepresidente = txtApellidosVicepresidente.getText();
        
        binomioSeleccionado.getMovimientoPolitico().setNombre(nuevoNombreMovimiento);
        binomioSeleccionado.getPresidente().setNombres(nuevosNombresPresidente);
        binomioSeleccionado.getPresidente().setApellidos(nuevosApellidosPresidente);
        binomioSeleccionado.getVicepresidente().setNombres(nuevosNombresVicepresidente);
        binomioSeleccionado.getVicepresidente().setApellidos(nuevosApellidosVicepresidente);
        
        limpiarTablaDeBinomios();
        mostrarDatosDeBinomios();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionBinomios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionBinomios().setVisible(true);
            }
        });
    }
    
    private void mostrarDatosDeBinomios() {
        for (Binomio b : FrmPrincipal.listaBinomios) {
            dtmTablaBinomios.addRow(new Object[]{b.getMovimientoPolitico().getNombre(),b.getPresidente().getApellidos()+" " +b.getPresidente().getNombres(),b.getVicepresidente().getApellidos()+ " "+ b.getVicepresidente().getNombres()});
        }
    }
    
    private void limpiarTablaDeBinomios() {
        for (int i = 0; i < tblBinomios.getRowCount(); i++) {
            dtmTablaBinomios.removeRow(i);
            i -= 1;
        }
    }

    private void obtenerBinomioSeleccionado() {
        filaSeleccionada = tblBinomios.getSelectedRow();
        binomioSeleccionado = listaBinomios.get(filaSeleccionada);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNombresPresidente;
    private javax.swing.JLabel lblApellidosPresidente;
    private javax.swing.JLabel lblApellidosVicepresidente;
    private javax.swing.JLabel lblDatosPresidente;
    private javax.swing.JLabel lblDatosVicepresidente;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JLabel lblNombreMovimientoPolitico;
    private javax.swing.JLabel lblNombresVicepresidente;
    private javax.swing.JPanel pnlDatosBinomio;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tblBinomios;
    private javax.swing.JTextField txtApellidosPresidente;
    private javax.swing.JTextField txtApellidosVicepresidente;
    private javax.swing.JTextField txtMovimientoPolitico;
    private javax.swing.JTextField txtNombresPresidente;
    private javax.swing.JTextField txtNombresVicepresidente;
    // End of variables declaration//GEN-END:variables
}
