package ventanas;

import herramientas.ComponentesDeVentana;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

public class Papeleta extends javax.swing.JFrame {

    public Papeleta() {
        initComponents();
        setSize(1130,650);
        setResizable(false);
        setTitle("ELECCIONES GENERALES 2023");
        setLocationRelativeTo(null);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblFondo,
                "src/imagenes/fondoPapeleta.png");
        ComponentesDeVentana.ajustarImagenAJLabel(lblEscudoEcudor, 
                "src/imagenes/escudoEcuador.png");
        ComponentesDeVentana.ajustarImagenAJLabel(lblLogoCNE, 
                "src/imagenes/logoPrincipal2.png");
        
        lblSubtitulo.setBackground(Color.WHITE);
        lblSubtitulo.setOpaque(true);
        ComponentesDeVentana.redondearBordesJLabel(lblSubtitulo, 10, 1);
        
        //Aqui se modifica el cuadro de eleccion de la lista
        lblLista1.setBackground(Color.WHITE);
        lblLista1.setOpaque(true);
        
        ComponentesDeVentana.ajustarImagenAJLabel(lblImagenLista, "src/imagenes/listas/alianzaUnionPorLaEsperanza.png");
        ComponentesDeVentana.ajustarImagenAJLabel(lblCuadroDeVoto, "src\\imagenes\\votoBlanco.png");
        ComponentesDeVentana.ajustarImagenAJLabel(lblImagenPresidente, "src/imagenes/candidatos/andresArauz.jpg");
        ComponentesDeVentana.ajustarImagenAJLabel(lblImagenVicepresidente, "src/imagenes/candidatos/carlosRabascall.jpg");
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(
                ClassLoader.getSystemResource("imagenes/logoCNEConFondo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoCNE = new javax.swing.JLabel();
        lblEscudoEcudor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblAlianza = new javax.swing.JLabel();
        lblUnion = new javax.swing.JLabel();
        lblEsperanza = new javax.swing.JLabel();
        lblNumeroLista = new javax.swing.JLabel();
        lblImagenLista = new javax.swing.JLabel();
        lblImagenPresidente = new javax.swing.JLabel();
        lblAndres = new javax.swing.JLabel();
        lblArauz = new javax.swing.JLabel();
        lblPresidente = new javax.swing.JLabel();
        lblVicepresidente = new javax.swing.JLabel();
        lblRabascall = new javax.swing.JLabel();
        lblCarlos = new javax.swing.JLabel();
        lblImagenVicepresidente = new javax.swing.JLabel();
        lblCuadroDeVoto = new javax.swing.JLabel();
        lblLista1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblLogoCNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 50, 100, 35));
        getContentPane().add(lblEscudoEcudor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 29, 35));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELECCIONES GENERALES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1130, -1));

        lblFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("07 DE FEBRERO DE 2023");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1130, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PRESIDENTA / PRESIDENTE - VICEPRESIDENTA / VICEPRESIDENTE");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1130, -1));

        lblSubtitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblSubtitulo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("SE ELIGE UN (1) BINOMIO PRESIDENCIAL");
        lblSubtitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 120, 800, 20));

        lblAlianza.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblAlianza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlianza.setText("ALIANZA");
        getContentPane().add(lblAlianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 10));

        lblUnion.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblUnion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnion.setText("UNION");
        getContentPane().add(lblUnion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 10));

        lblEsperanza.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblEsperanza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsperanza.setText("ESPERANZA");
        getContentPane().add(lblEsperanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 10));

        lblNumeroLista.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNumeroLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroLista.setText("1-5");
        getContentPane().add(lblNumeroLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        lblImagenLista.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblImagenLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblImagenLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 70));

        lblImagenPresidente.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblImagenPresidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblImagenPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 60, 40));

        lblAndres.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblAndres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAndres.setText("ANDRES");
        getContentPane().add(lblAndres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 60, 10));

        lblArauz.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblArauz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArauz.setText("ARAUZ");
        getContentPane().add(lblArauz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 60, 10));

        lblPresidente.setFont(new java.awt.Font("Arial", 1, 7)); // NOI18N
        lblPresidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresidente.setText("PRESIDENTE");
        getContentPane().add(lblPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 60, 10));

        lblVicepresidente.setFont(new java.awt.Font("Arial", 1, 6)); // NOI18N
        lblVicepresidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVicepresidente.setText("VICEPRESIDENTE");
        getContentPane().add(lblVicepresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 60, 10));

        lblRabascall.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblRabascall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRabascall.setText("RABASCALL");
        getContentPane().add(lblRabascall, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 60, 10));

        lblCarlos.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblCarlos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarlos.setText("CARLOS");
        getContentPane().add(lblCarlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 60, 10));

        lblImagenVicepresidente.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblImagenVicepresidente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenVicepresidente.setText("jLabel3");
        getContentPane().add(lblImagenVicepresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 60, 40));

        lblCuadroDeVoto.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblCuadroDeVoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblCuadroDeVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 40, 30));

        lblLista1.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        lblLista1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 440));

        lblFondo.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Papeleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Papeleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Papeleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Papeleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Papeleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlianza;
    private javax.swing.JLabel lblAndres;
    private javax.swing.JLabel lblArauz;
    private javax.swing.JLabel lblCarlos;
    private javax.swing.JLabel lblCuadroDeVoto;
    private javax.swing.JLabel lblEscudoEcudor;
    private javax.swing.JLabel lblEsperanza;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagenLista;
    private javax.swing.JLabel lblImagenPresidente;
    private javax.swing.JLabel lblImagenVicepresidente;
    private javax.swing.JLabel lblLista1;
    private javax.swing.JLabel lblLogoCNE;
    private javax.swing.JLabel lblNumeroLista;
    private javax.swing.JLabel lblPresidente;
    private javax.swing.JLabel lblRabascall;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnion;
    private javax.swing.JLabel lblVicepresidente;
    // End of variables declaration//GEN-END:variables
}
